use external docker image
Compilerbau/Lecture pull request #106
Opened 2021-11-05 18:49 UTC by jposselt

Fixes #19

- maintain build scripts in a separate repository
- a pre-build image is stored in the Github container registry
- actions just pull the image from the repository

2021-11-05 19:45 UTC, jposselt commented
@cagix Funktioniert noch nicht richtig. Liegt glaube ich daran, dass die ganze Action im Container läuft anstatt das Image zu laden und für jeden Befehl einen Container zu starten. Um das zu fixen müsste ich entweder hier die Makefile noch mal ändern oder im Image noch git installieren. Ich weiß auch nicht, ob das `runs-on: ubuntu-latest` nötig ist, wenn man sowieso alles in einem eigenen Container packt.

2021-11-06 07:21 UTC, cagix commented
> @cagix Funktioniert noch nicht richtig. Liegt glaube ich daran, dass die ganze Action im Container läuft anstatt das Image zu laden und für jeden Befehl einen Container zu starten. Um das zu fixen müsste ich entweder hier die Actions noch mal ändern oder im Image noch git installieren. Ich weiß auch nicht, ob das `runs-on: ubuntu-latest` nötig ist, wenn man sowieso alles in einem eigenen Container packt.

Hmmja, darüber bin ich vor nem haben Jahr auch schon gestolpert und habe es aufgegeben, weil es zuviel gehakelt hatte. Deshalb die eigene Action, die dann wieder einen eigenen Docker nutzt (bzw. bei jedem Lauf neu baut).

Ich glaube, der Trick ist, die Action selbst tatsächlich doch wieder hier im Repo zu definieren und im Workflow zu nutzen. Allerdings sollte die Action dann nicht den Docker neu bauen, sondern Deinen Docker aus der Registry ziehen. Das müsste irgendwie gehen.

Die Alternative, den Docker einmal zu starten und dann den Rest in einem Rutsch darin zu erledigen, finde ich aber sehr spannend. Das war mein ursprünglicher Ansatz. Allerdings musst Du dann einen Weg finden, mit einem `make ...` in den Docker zu wechseln und die restlichen Make-Abhängigkeiten dann innerhalb des Containers aufzulösen. Imho läuft das auf ein zweites "Shadow"-Make zurück: Im ersten hat man die direkt anspringbaren Targets (`web`, `slides`, `semantics/symboltables/intro`, ...), darüber wird der Container gestartet mit einem Entrypoint `make ...`, wo das zweite Makefile aufgerufen wird und dann die Sachen tatsächlich erledigt, und zwar direkt und komplett innerhalb des Containers.

2021-11-06 07:22 UTC, cagix commented
> Ich weiß auch nicht, ob das `runs-on: ubuntu-latest` nötig ist, wenn man sowieso alles in einem eigenen Container packt.

Sollte aber irgendwo bei Github dokumentiert sein. Leider ist das extrem unübersichtlich :/

2021-11-06 07:27 UTC, cagix requested changes

2021-11-06 07:27 UTC, cagix commented on .github/workflows/hugo.yaml
>        - uses: actions/checkout@v2
Nach meinem Verständnis wird jetzt der Container als Ausführungsumgebung genommen. Kann/Versteht der denn die `actions/checkout@v2`?

Vermutlich müsste man das jetzt in drei Schritte splitten? (1) Auschecken, (2) im Container bauen, (3) GH-Pages deployen ... D.h. man müsste die Artefakte in jedem Schritt zwischenspeichern und dann im nächsten Schritt wieder abrufen. Dazu gibts aber irgendwas von GH (vgl. Doku).

2021-11-06 10:19 UTC, jposselt commented on .github/workflows/hugo.yaml
>        - uses: actions/checkout@v2
Das Auschecken schlägt zur Zeit fehl, weil im Container kein Git installiert ist und Submodules von der Fallback REST API nicht unterstützt werden. Zumindest interpretiere ich die Fehlermeldung so. Deshalb wollte ich im Image auch noch mal Git hinzufügen und sehen, ob es dann geht.

Eine Alternative wäre noch sich in der Action bei der Container Registry anzumelden und das Image zu ziehen. Dann könnte man wahrscheinlich auch die `.github/actions/alpine-pandoc-hugo/action.yaml` weiter benutzen. Die führt ja nur Make im Container aus.

2021-11-06 10:36 UTC, cagix commented on .github/workflows/hugo.yaml
>        - uses: actions/checkout@v2
> Eine Alternative wäre noch sich in der Action bei der Container Registry anzumelden und das Image zu ziehen. Dann könnte man wahrscheinlich auch die `.github/actions/alpine-pandoc-hugo/action.yaml` weiter benutzen. Die führt ja nur Make im Container aus.

das wäre imho am einfachsten ...

2021-11-06 11:13 UTC, jposselt commented on .github/workflows/hugo.yaml
>        - uses: actions/checkout@v2
Wenn ich es richtig verstehe baut die `action.yml` ja selber auch noch mal ein Image basierend auf dem Dockerfile und führt das als Parameter übergeben Kommando darin aus. Funktioniert also doch nicht mit einem schon existierenden Image.

2021-11-06 11:32 UTC, cagix commented on .github/workflows/hugo.yaml
>        - uses: actions/checkout@v2
ja, aber kann die nicht auch ein existierendes image ziehen?

2021-11-06 11:42 UTC, jposselt commented on .github/workflows/hugo.yaml
>        - uses: actions/checkout@v2
Ja, habe ich gerade ausprobiert und funktioniert. Die automatisch anlaufende Action schlägt natürlich fehl, weil kein `docker-image` Foliensatz existiert aber wenn man manuell die Action zum bauen aller Foliensätze anstößt lauft es durch.

2021-11-06 11:51 UTC, jposselt commented
@cagix Das ziehen des Image von der Registry dauert natürlich auch ein paar Sekunden. Am Ende scheinen sich die Ansätze nicht viel zu nehmen.

2021-11-06 12:03 UTC, cagix commented
> @cagix Das ziehen des Image von der Registry dauert natürlich auch ein paar Sekunden. Am Ende scheinen sich die Ansätze nicht viel zu nehmen.

aber das ist doch deutlich schneller also die 15…20 sekunden für das bauen des containers, oder?

2021-11-06 12:10 UTC, jposselt commented
> 
> 
> > @cagix Das ziehen des Image von der Registry dauert natürlich auch ein paar Sekunden. Am Ende scheinen sich die Ansätze nicht viel zu nehmen.
> 
> aber das ist doch deutlich schneller also die 15…20 sekunden für das bauen des containers, oder?

Nicht wirklich. Ich habe zwar nur einen Datenpunkt aber das Ziehen dauert auch 15 Sekunden.

2021-11-06 12:54 UTC, cagix commented
> > > @cagix Das ziehen des Image von der Registry dauert natürlich auch ein paar Sekunden. Am Ende scheinen sich die Ansätze nicht viel zu nehmen.
> > 
> > 
> > aber das ist doch deutlich schneller also die 15…20 sekunden für das bauen des containers, oder?
> 
> Nicht wirklich. Ich habe zwar nur einen Datenpunkt aber das Ziehen dauert auch 15 Sekunden.

wow, das ist lange. ist das nur einmal so gewesen oder bei mehreren versuchen? 

dann lohnt es sich vermutlich nicht, hier weiter nachzugehen ...

2021-11-06 12:56 UTC, cagix commented
Ich frage mich, wie das die vorgefertigten Actions machen (Checkout, PeaceIris/Hugo, ...)? Die haben doch teilweise auch einen Docker-Container in der Hinterhand? Der Aufruf dieser Actions geht ja i.d.R. sehr schnell ... Liegt das daran, dass die Actions irgendwo als solche hinterlegt sind und damit dann gecached werden (inkl. Docker)?

2021-11-06 13:25 UTC, jposselt commented
> wow, das ist lange. ist das nur einmal so gewesen oder bei mehreren versuchen?

Bisher nur einmal.

> Ich frage mich, wie das die vorgefertigten Actions machen (Checkout, PeaceIris/Hugo, ...)? Die haben doch teilweise auch einen Docker-Container in der Hinterhand? Der Aufruf dieser Actions geht ja i.d.R. sehr schnell ... Liegt das daran, dass die Actions irgendwo als solche hinterlegt sind und damit dann gecached werden (inkl. Docker)?

Ich weiß, dass man für das bauen von Images in Actions die Layer cachen kann. Dafür gibt es auch schon [fertige Actions](https://github.com/whoan/docker-build-with-cache-action) . Fragt sich, ob das wirklich einen Unterschied macht.

2021-11-09 15:05 UTC, closed without merging