replaced images
Compilerbau/Lecture pull request #109
Opened 2021-11-09 17:13 UTC by jposselt

Fixes #108

Veraltete Bilder ausgetauscht

2021-11-09 17:18 UTC, jposselt commented
@cagix Soll ich die Source-Datei auch noch mit dazu packen? Ist allerdings eine `drawio` Datei. Eventuell müsste man auch noch mal die größe der Bilder in der `index.md` anpassen.

2021-11-09 18:04 UTC, jposselt commented
Ich habe mal versucht die Bilder mit Graphviz zu reproduzieren. Vielleicht nicht ganz so schön wie die anderen aber leichter zu modifizieren.

![cpp-toolchain](https://user-images.githubusercontent.com/24254997/140979059-c172f34f-16b7-4049-849e-7ef1089f5aeb.png)
![findbugs](https://user-images.githubusercontent.com/24254997/140979062-30e5b2fa-3380-43ec-bad8-bda980335a3a.png)
![c-toolchain](https://user-images.githubusercontent.com/24254997/140979063-c4cc6f80-10be-4036-b690-fd6fb890937d.png)
er

2021-11-09 18:28 UTC, cagix commented
die dot-dinger finde ich wesentlich schöner als die manuell gemalten teile!

2021-11-09 18:30 UTC, cagix requested changes
bitte die bilder löschen und mit den dot-bildern ersetzen :)  die sehen nämlich spitze aus!

2021-11-09 19:55 UTC, cagix approved these changes
👍

2021-11-10 07:47 UTC, jposselt commented
@cagix Gibt es eigentlich einen Grund warum die SLIDES Action deaktiviert ist?

2021-11-10 07:48 UTC, cagix commented
> @cagix Gibt es eigentlich einen Grund warum die SLIDES Action deaktiviert ist?

die hat mich zwischendrin nur genervt (wenn ich auf anderen inhalten als den lectures unterwegs war), und da ich das ergebnis derzeit nicht brauche, muss ja auch keine rechenzeit verschwendet werden ...

2021-11-10 07:58 UTC, cagix commented
> 👍

@jposselt sieht gut aus, kannst mergen :)  danke

2021-11-10 08:08 UTC, jposselt commented
> 
> 
> > 👍
> 
> @jposselt sieht gut aus, kannst mergen :) danke

Dazu fehlt mir die Berechtigung.

2021-11-10 08:19 UTC, cagix commented
> > > 👍
> > 
> > 
> > @jposselt sieht gut aus, kannst mergen :) danke
> 
> Dazu fehlt mir die Berechtigung.

so soll es sein 😎🙈

2021-11-10 08:20 UTC, merged

2021-11-10 08:21 UTC, cagix commented
@jposselt mange takk!