interpretation/syntaxdriven
Compilerbau/Lecture pull request #52
Opened 2021-09-16 14:00 UTC by AMatutat

#34

- todo: motivation

2021-09-16 14:49 UTC, cagix approved these changes
👍

2021-11-15 06:05 UTC, cagix commented
@Fabian-Hu ich assigne den pr mal an dich für die uml-diagramme und so. wenn du damit fertig bist, assigne bitte wieder zurück an mich.

2021-11-15 13:05 UTC, Fabian-Hu commented
@cagix ich hab drei uml Diagramme hinzugefügt. Die Diagramme bauen auf einander auf und sollen am Ende den Codesnipsel ersetzen. Damit du dir das noch anschauen kannst hab ich die Codesnipsel noch nicht gelöscht. Für dem Bereich Listener hab ich keine UML Diagramme erstellt, da ich denke, dass der Code hier wichtiger sein könnte und ein UML Diagramm nur unnötig groß wird.

Das end Diagramm:
![ParserRuleContext3](https://user-images.githubusercontent.com/32959586/141786837-bc7667f3-17f7-4ee2-9f25-2f9b69ad8e9f.png)

2021-11-15 15:24 UTC, cagix requested changes
ein paar kleinigkeiten ... :)

und ich glaube, in den uml-diagrammen müssten die pfeile alle andersrum, oder?

2021-11-15 15:24 UTC, cagix commented on markdown/interpretation/syntaxdriven/index.md
> +        :::
wieso rückst du die ":::" hier extra ein?

2021-11-15 15:24 UTC, cagix commented on markdown/interpretation/syntaxdriven/index.md
> +        :::
dito

2021-11-15 15:24 UTC, cagix commented on markdown/interpretation/syntaxdriven/index.md
> +::: {.column width="35%"}
wieso nimmst du hier eine columns-umgebung? entweder müsste der code obendrüber auch in eine spalte, damit die quasi nebeneinander in der folie liegen, oder die columns-umgebung hier kann einfach weg. 

ggf. durch "`::: center`" ersetzen, damit die abbildung zentriert wird.

2021-11-15 15:24 UTC, cagix commented on markdown/interpretation/syntaxdriven/index.md
> +::: {.column width="35%"}
dito: columns?

2021-11-15 15:24 UTC, cagix commented on markdown/interpretation/syntaxdriven/index.md
> +::: {.column width="35%"}
dito: columns?

2021-11-15 15:38 UTC, cagix commented
> @cagix ich hab drei uml Diagramme hinzugefügt. Die Diagramme bauen auf einander auf und sollen am Ende den Codesnipsel ersetzen. Damit du dir das noch anschauen kannst hab ich die Codesnipsel noch nicht gelöscht. 

Teilweise sind Kommentare am Code, die nochmal Dinge erklären sollen. Die könnten als "Note" ins UML?

> Für dem Bereich Listener hab ich keine UML Diagramme erstellt, da ich denke, dass der Code hier wichtiger sein könnte und ein UML Diagramm nur unnötig groß wird.

ja, das macht sinn. allerdings würde sich für die codeblöcke "`public interface calc2Listener extends ParseTreeListener`" und "`public class calc2BaseListener implements calc2Listener`" eigentlich ein uml als ersatz geradezu anbieten, oder? dito für "`public interface calc2Visitor<T> extends ParseTreeVisitor<T>`"  und "`public class calc2BaseVisitor<T> extends AbstractParseTreeVisitor<T> implements calc2Visitor<T>`" ...

2021-11-15 17:33 UTC, Fabian-Hu commented
So ich hab alles angepasst und für die Listener und den Visitor UML Diagramme erstellt. Mit den verdrehten Pfeilen, da muss ich geschlafen haben ;)

2021-11-18 13:03 UTC, cagix requested changes

2021-11-18 13:03 UTC, cagix commented on markdown/interpretation/syntaxdriven/index.md
> +	    :::
dein letzter commit hat hier wieder was eingerückt ...

2021-11-18 13:03 UTC, cagix commented on markdown/interpretation/syntaxdriven/index.md
> +	    :::
dito

2021-12-01 13:55 UTC, merged