interpretation/astdriven part1
Compilerbau/Lecture pull request #53
Opened 2021-09-16 14:05 UTC by AMatutat

Fixes #34

todo: motivation

2021-09-16 14:50 UTC, cagix approved these changes
👍

2021-11-15 06:05 UTC, cagix commented
@Fabian-Hu ich assigne den pr mal an dich für die uml-diagramme und so. wenn du damit fertig bist, assigne bitte wieder zurück an mich.

2021-11-15 13:20 UTC, Fabian-Hu commented
@cagix hier habe ich ein UML Diagramm für die Interpreter Klasse erstellt damit könnte man auch hier den Codesnipsel für den Interpreter ersetzen. Die anderen Codesnipsel drehen sich eher um die Umsetzung von varDecl, assign, block und ifstat.

Das Diagramm
![interpreter](https://user-images.githubusercontent.com/32959586/141788327-6d052b83-b768-408b-bb63-3fced6645408.png)
:

2021-11-15 15:29 UTC, cagix requested changes
danke. ich glaube, die uml-pfeile sind auch hier verdreht, oder?

könntest du bei den "Quelle: nach Nystrom" bitte nach den Dateien im Github von Crafting Interpreters suchen, ob Du die Stellen findest? Dann könnten wir die Referenzen korrigieren.

2021-11-15 15:29 UTC, cagix commented on markdown/interpretation/astdriven-part1/index.md
> +::: {.column width="35%"}
column?

2021-11-15 15:29 UTC, cagix commented on markdown/interpretation/astdriven-part1/index.md
> +[[Quelle: nach [@Nystrom2018], Kapitel "Functions"]{.origin}]{.notes}
Du könntest bitte mal im Quellcode vom Nystrom suchen, ob Du diese Stelle findest. Dann könnte die Referenz direkt auf seinen Code zeigen (der steht nämlich unter MIT).

2021-11-15 15:39 UTC, cagix commented
> @cagix hier habe ich ein UML Diagramm für die Interpreter Klasse erstellt damit könnte man auch hier den Codesnipsel für den Interpreter ersetzen. Die anderen Codesnipsel drehen sich eher um die Umsetzung von varDecl, assign, block und ifstat.

ja, die letzteren schnipsel sollten wohl besser code bleiben, hier geht es ja eher um die inhalte.

2021-11-17 12:59 UTC, Fabian-Hu commented
@cagix schau dir mal die Quellenangabe an. Ich hab mich an die alte Quellenangabe gehalten und habe die Klasse aus dem Github direkt dahinter verlinkt.

2021-11-17 15:38 UTC, cagix requested changes
fast :)

2021-11-17 15:38 UTC, cagix commented on markdown/interpretation/astdriven-part1/index.md
> +    comment: "Kapitel 'Functions' "
sieht gut aus, nur der Key ist mittlerweile "Nystrom2021"

2021-11-17 15:38 UTC, cagix commented on markdown/interpretation/astdriven-part1/index.md
> +[[Quelle: nach [@Nystrom2018], Kapitel "Functions", [Interpreter.java](https://github.com/munificent/craftinginterpreters/blob/master/java/com/craftinginterpreters/lox/Interpreter.java)]{.origin}]
ersetze die Zeile mal mit 

```
[Quelle: nach [@Nystrom2021], [`Interpreter.java`](https://github.com/munificent/craftinginterpreters/blob/master/java/com/craftinginterpreters/lox/Interpreter.java) ([MIT](https://github.com/munificent/craftinginterpreters/blob/master/LICENSE))]{.origin}
```

2021-12-01 14:03 UTC, merged