interpretation/astdriven-part2
Compilerbau/Lecture pull request #54
Opened 2021-09-16 14:09 UTC by AMatutat

#34 

todo: motivation

2021-09-16 14:52 UTC, cagix requested changes
kleinkram :)

2021-09-16 14:52 UTC, cagix commented on markdown/interpretation/astdriven-part2/index.md
> +    comment: "Kapitel "A Tree-Walk Interpreter" "
ugh, das geht schief :)  nimm bitte für die inneren anführungszeichen einfach hochkommas

2021-09-16 16:52 UTC, cagix commented
aye 👍

2021-11-15 06:04 UTC, cagix commented
@Fabian-Hu ich assigne den pr mal an dich für die uml-diagramme und so. wenn du damit fertig bist, assigne bitte wieder zurück an mich.

2021-11-15 13:49 UTC, Fabian-Hu commented
@cagix hier habe ich das alte UML Diagramm angepasst und für die einzelnen Schritte aufgeteilt. Außerdem habe ich unnötige Notes entfernt, da diese bereits im Codesnipsel standen.

2021-11-15 15:34 UTC, cagix requested changes
zwischen "Instance" und "Klass" fehlt noch ein Pfeil.

Sollten wir das mit den anderen UMLs kompatibel machen? Zuletzt meine ich hatten wir "Clazz" statt "Klass"?

2021-11-15 15:34 UTC, cagix commented on markdown/interpretation/astdriven-part2/index.md
> +::: {.column width="35%"}
columns?

2021-11-15 15:34 UTC, cagix commented on markdown/interpretation/astdriven-part2/index.md
> +[Quelle: nach [@Nystrom2018], Kapitel "Functions"]{.origin}
Bitte auch hier nochmal nach den ursprünglichen Sourcen suchen, damit wir direkt auf den Code verweisen können

2021-11-15 15:34 UTC, cagix commented on markdown/interpretation/astdriven-part2/index.md
> +::: {.column width="35%"}
columns?

2021-11-15 15:34 UTC, cagix commented on markdown/interpretation/astdriven-part2/index.md
> +::: {.column width="35%"}
columns?

2021-11-15 15:44 UTC, cagix commented
> @cagix hier habe ich das alte UML Diagramm angepasst und für die einzelnen Schritte aufgeteilt. Außerdem habe ich unnötige Notes entfernt, da diese bereits im Codesnipsel standen.

du meinst die notes in `classes.*`, oder? 

ja, die stehen auch in den codeschnipseln. die sind aber in den folien nicht zu sehen, die uml-diagramme schon. insofern waren die notes schon relevant (für mich). kannst du die wieder reintun?

2021-11-15 15:46 UTC, cagix commented
> zwischen "Instance" und "Klass" fehlt noch ein Pfeil.

argl. das ist ja keine vererbungsbeziehung, sondern nur eine "kennt/nutzt". passt also ohne pfeil :) sorry.

2021-12-01 14:12 UTC, merged