Semantics/attribgrammars
Compilerbau/Lecture pull request #80
Opened 2021-09-28 15:20 UTC by jposselt

#34

Änderungen:

- Bilder: PDF -> PNG (PDF in Webversion nicht darstellbar)
- Latex Tabellen -> Markdown Tabellen
- Code: Highlighting

TODOs:

- Beispiel: Geerbte Attribute
- Beispiel: Probleme mit geerbten Attributen
- Beispiel: Typen für geerbte Attribute

2021-09-28 15:31 UTC, cagix requested changes
@jposselt Bitte keine PDF-Dateien einchecken, wenn sie nicht gebraucht werden. 

Bei den aus den .dot-Files erstellten Abbildungen muss ich wohl noch ein Make-Target nachreichen, dann können auch die entsprechenden .png-Abbildungen raus aus dem Repo.

2021-09-28 17:21 UTC, cagix commented
@jposselt Oh, und bitte keine Merges vom Master in einen Feature-Branch! Das macht den flexiblen Umgang mit den Feature-Branches kaputt ... Ich werde deshalb den letzten Commit zurücksetzen.

2021-09-28 17:27 UTC, cagix commented
> @jposselt Oh, und bitte keine Merges vom Master in einen Feature-Branch! Das macht den flexiblen Umgang mit den Feature-Branches kaputt ... Ich werde deshalb den letzten Commit zurücksetzen.

Wenn Du die aktuellen Änderung im Master im Featurebranch haben willst, dann mach einen Rebase: `git rebase master <feature> && git push -f origin <feature>` ... Bitte nicht die Weboberfläche oder App von Github nehmen, die mergt immer den Master in die Feature-Branches und macht hinterher das Leben schwer.

2021-09-28 17:52 UTC, cagix commented
@jposselt @bcg7 Ich habe in #81 Support für das Übersetzen von Dot-Files nach .png hinzugefügt. Es ist also nicht notwendig, die generierten Bilder (PDF, PNG) hier mit einzuchecken. 

@jposselt Bitte einmal lokal rebasen `git fetch --prune && git checkout master && git pull && git rebase master semantics/attribgrammars && git push -f origin semantics/attribgrammars", dann steht diese Funktionalität auch hier zur Verfügung und Du kannst in einem weiteren Commit die Bilder wieder löschen. Durch den Squash-Merge am Ende landen die dann auch nicht temporär im Repo.

2021-09-28 19:14 UTC, jposselt commented
@cagix Die aus Dot-Files generierten Bilder sehen bei mir so aus.
![ast](https://user-images.githubusercontent.com/24254997/135150831-a7e71bba-2e66-47cf-bb41-9ec7fe502259.png)
Funktioniert das denn bei dir, oder liegt das wieder an meinem System?

2021-09-28 19:23 UTC, jposselt commented
Problem liegt anscheinend wieder bei mir. Die von Gihub generierte Ausgabe sieht in Ordnung aus.

2021-09-28 20:01 UTC, cagix commented
> Problem liegt anscheinend wieder bei mir. Die von Gihub generierte Ausgabe sieht in Ordnung aus.

ich musste das docker image aktualisieren, da fehlten die fonts :(

2021-11-05 16:49 UTC, jposselt commented
@bcg7 Bitte noch mal prüfen, ob alles da und in Ordnung ist.

2021-11-07 11:29 UTC, bcg7 commented
@jposselt 
kannst du bitte noch die Folie mit der Compiler-Pipeline noch herausnehmen? Damit haben wir, glaube ich, alle notwendigen Änderungen besporchen, und du kannst pushen.
Ich antworte ncihtmehr per Mail auf die Mails von github, sondern kommentire nur noch direkt im github. Dies ist jetzt der zweite Fall, dass eine Mail hier nie erschient (war vorgestern,)

2021-11-07 11:36 UTC, cagix commented
> Ich antworte ncihtmehr per Mail auf die Mails von github, sondern kommentire nur noch direkt im github. Dies ist jetzt der zweite Fall, dass eine Mail hier nie erschient (war vorgestern,)

@bcg7 Das liegt am Mail-Client. Mit Thunderbird und unter Android kann ich zwar auch auf die Mails antworten, die tauchen dann aber nicht hier im Github als Kommentar auf (werden also stillschweigend abgewiesen). Unter MacOS geht es per Mail, aber dann hängt in den Kommentaren immer so viel Kram noch dran (das ganze Quoting und so). Deshalb mache ich das auch immer direkt im Browser (oder auf dem Handy in der App, das ist etwas angenehmer, auch wenn da viele Optionen fehlen, die es im Browser gibt).

2021-11-07 11:38 UTC, cagix commented
> @jposselt
> kannst du bitte noch die Folie mit der Compiler-Pipeline noch herausnehmen? Damit haben wir, glaube ich, alle notwendigen Änderungen besporchen, und du kannst pushen.

@bcg7 @jposselt Wenn ihr soweit seid, dass ich mergen kann/soll und auch die Seiten dann ins ILIAS stellen soll, setzt den Assignee in diesem Pull-Request bitte einfach auf mich.

2021-11-07 11:38 UTC, bcg7 commented
Ich dachte bisher, das passiere nur vereinzelt, aber jetzt weiß ich ja Bescheid.

2021-11-07 11:49 UTC, cagix commented
> Ich dachte bisher, das passiere nur vereinzelt, aber jetzt weiß ich ja Bescheid.

das liegt irgendwie daran, welche felder der mailclient bei der antwort mitsendet (oder auch nicht). wenn da die einträge fehlen, die github benötigt, um die mail einem kommentar o.ä. zuzuordnen, wird die mail ignoriert ...

ist bei unserem gitlab aber auch so, nur noch schlimmer ;)

2021-11-07 11:54 UTC, cagix approved these changes
lgtm :)

@bcg7 zu bison gibt es ja einen vortrag seitens der studis. ich habe gesehen, dass hier noch recht viel bison-material drin ist. wird das dann für die studis zu "klein" vom thema her?

2021-11-07 12:35 UTC, merged